# Generated by Django 3.0.6 on 2020-05-18 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fio', models.CharField(default='', max_length=100, verbose_name='ФИО')),
                ('avatar', models.ImageField(blank=True, default='default.png', upload_to='user_avatar', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профиль пользователя',
            },
        ),
    ]
