# Generated by Django 3.0.6 on 2020-05-18 03:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=100, verbose_name='ФИО')),
                ('start_day_work', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятнца'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], default='ПН', max_length=60, verbose_name='Начало работы')),
                ('end_day_work', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятнца'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], default='ПТ', max_length=60, verbose_name='Конец работы')),
                ('room', models.IntegerField(default=0, verbose_name='Кабинет')),
                ('avatar', models.ImageField(blank=True, default='default_doc.png', upload_to='doc_avatar', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'врача',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'Специальности врачей',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_start', models.TimeField(blank=True, verbose_name='Понедельник начало')),
                ('mo_end', models.TimeField(blank=True, verbose_name='Понедельник конец')),
                ('tu_start', models.TimeField(blank=True, verbose_name='Вторник начало')),
                ('tu_end', models.TimeField(blank=True, verbose_name='Вторник конец')),
                ('we_start', models.TimeField(blank=True, verbose_name='Среда начало')),
                ('we_end', models.TimeField(blank=True, verbose_name='Среда конец')),
                ('th_start', models.TimeField(blank=True, verbose_name='Четверг начало')),
                ('th_end', models.TimeField(blank=True, verbose_name='Четверг конец')),
                ('fr_start', models.TimeField(blank=True, verbose_name='Пятница начало')),
                ('fr_end', models.TimeField(blank=True, verbose_name='Пятница конец')),
                ('time_step', models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='Время на одного пациента')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lk.Doctors', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'Расписание врача',
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.Speciality'),
        ),
    ]
